spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: false

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel
      schema:
        idempotency-key:
          ttl-min: 5

  kafka:
    bootstrap-servers: localhost:9092
    topics:
      transactions:
        check:
          name: check_transaction
          partitions: 1
          replicas: 1

    producer:
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://localhost:8087"
    consumer:
      enable-auto-commit: true
      group-id: "post-service-group"
      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      autoOffsetReset: "earliest"
      properties:
        schema:
          registry:
            url: "http://localhost:8087"
        specific:
          avro:
            reader: "true"



server:
  port: 8081

logging:
  level:
    root: info

retry:
  config:
    max-attempts: 3
    initial-interval-ms: 1000
    multiplier: 2.0
    delay: 1000
    max-interval-ms: 10_000

