spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel
      schema:
        rule:
          ttl-days: 1

  kafka:
    bootstrap-servers: localhost:9092
    topics:
      transactions:
        check:
          name: check_transaction
          partitions: 1
          replicas: 1
      rules:
        reload:
          name: rules_reload
          partitions: 1
          replicas: 1
    consumer:
      enable-auto-commit: true
      group-id: "post-service-group"
      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      autoOffsetReset: "earliest"
      properties:
        schema:
          registry:
            url: "http://localhost:8087"
        specific:
          avro:
            reader: "true"

server:
  port: 8082

logging:
  level:
    root: info


risk:
  threshold: 2

scheduling:
  redis:
    rules:
      reload: 0 */15 * * * *

retry:
  config:
    max-attempts: 3
    initial-interval-ms: 1000
    multiplier: 2.0
    delay: 1000
    max-interval-ms: 10_000

thread-pool:
  async:
    rule:
      core-pool-size: 5
      max-pool-size: 10
      queue-capacity: 1000
    commit:
      core-pool-size: 5
      max-pool-size: 10
      queue-capacity: 1000
