{
  "type": "record",
  "name": "TransactionRiskCheckEvent",
  "namespace": "com.financeRadar.manticore.dto.avro",
  "fields": [
    {"name": "amount", "type": "string"},
    {"name": "senderId", "type": "string"},
    {"name": "receiverId", "type": "string"},
    {"name": "transactionId", "type": "string"},
    {"name": "correlationId", "type": "string"},
    {"name": "idempotencyKey", "type": "string"},
    {"name": "currency", "type": "string"},
    {"name": "createdAt", "type": {"type": "long", "logicalType": "timestamp-millis"}}
  ]
}